name: Build APK Google Studio
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cài đặt Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Khởi tạo nền tảng Android tự động
        run: flutter create . --org com.studio.googlestudio --platforms=android

      - name: Cài thư viện
        run: flutter pub get

      - name: Đóng gói APK
        run: flutter build apk --release

      - name: Lưu trữ file APK
        uses: actions/upload-artifact@v4
        with:
          name: Google-Studio-App
          path: build/app/outputs/flutter-apk/app-release.apk
